/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana1;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardomedina
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGPuesto = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        lblNEmpleado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblOficina = new javax.swing.JLabel();
        sp_NEmpleado = new javax.swing.JSpinner();
        cb_oficina = new javax.swing.JComboBox<>();
        lblEadad = new javax.swing.JLabel();
        spnEdad = new javax.swing.JSpinner();
        rbtn_Vendedor = new javax.swing.JRadioButton();
        rbtn_gerente = new javax.swing.JRadioButton();
        rbtn_director = new javax.swing.JRadioButton();
        lbl_fecha = new javax.swing.JLabel();
        ftext_contratacion = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        btn_archivo = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        btn_edicion = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario");
        setBounds(new java.awt.Rectangle(0, 25, 400, 400));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lblNombre.setLabelFor(txtNombre);
        lblNombre.setText("Nombre: ");
        lblNombre.setToolTipText("Nombre del Empleado");
        lblNombre.setBounds(new java.awt.Rectangle(40, 20, 80, 26));
        lblNombre.setMaximumSize(new java.awt.Dimension(80, 26));
        lblNombre.setMinimumSize(new java.awt.Dimension(80, 26));
        lblNombre.setPreferredSize(new java.awt.Dimension(80, 26));
        getContentPane().add(lblNombre);
        lblNombre.setBounds(40, 20, 80, 26);

        txtNombre.setToolTipText("Nombre del Empleado");
        txtNombre.setMaximumSize(new java.awt.Dimension(80, 26));
        txtNombre.setMinimumSize(new java.awt.Dimension(80, 26));
        txtNombre.setPreferredSize(new java.awt.Dimension(80, 26));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(160, 20, 80, 26);

        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_guardar.setMaximumSize(new java.awt.Dimension(100, 35));
        btn_guardar.setMinimumSize(new java.awt.Dimension(100, 35));
        btn_guardar.setPreferredSize(new java.awt.Dimension(100, 35));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar);
        btn_guardar.setBounds(150, 310, 100, 35);

        lblNEmpleado.setLabelFor(sp_NEmpleado);
        lblNEmpleado.setText("N. Empleado: ");
        lblNEmpleado.setToolTipText("Numero de empleado");
        lblNEmpleado.setBounds(new java.awt.Rectangle(40, 60, 90, 26));
        lblNEmpleado.setMaximumSize(new java.awt.Dimension(90, 26));
        lblNEmpleado.setMinimumSize(new java.awt.Dimension(90, 26));
        lblNEmpleado.setPreferredSize(new java.awt.Dimension(90, 26));
        getContentPane().add(lblNEmpleado);
        lblNEmpleado.setBounds(40, 60, 90, 26);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 110, 0, 0);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 0, 0);

        lblOficina.setLabelFor(cb_oficina);
        lblOficina.setText("Oficina: ");
        lblOficina.setToolTipText("En que oficina trabaja el empleado");
        lblOficina.setBounds(new java.awt.Rectangle(40, 100, 80, 26));
        lblOficina.setMaximumSize(new java.awt.Dimension(80, 26));
        lblOficina.setMinimumSize(new java.awt.Dimension(80, 26));
        lblOficina.setPreferredSize(new java.awt.Dimension(80, 26));
        getContentPane().add(lblOficina);
        lblOficina.setBounds(40, 100, 80, 26);

        sp_NEmpleado.setModel(new javax.swing.SpinnerNumberModel(1000, null, null, 1));
        sp_NEmpleado.setToolTipText("Numero asignado al empleado");
        sp_NEmpleado.setBounds(new java.awt.Rectangle(160, 60, 80, 26));
        sp_NEmpleado.setMaximumSize(new java.awt.Dimension(80, 26));
        sp_NEmpleado.setMinimumSize(new java.awt.Dimension(80, 26));
        sp_NEmpleado.setPreferredSize(new java.awt.Dimension(80, 26));
        sp_NEmpleado.setRequestFocusEnabled(false);
        getContentPane().add(sp_NEmpleado);
        sp_NEmpleado.setBounds(160, 60, 80, 26);

        cb_oficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Denver", "Los Ángeles", "Ciudad de México", "Guadalajara", "San Francisco", "Toluca", "Monterrey", "" }));
        cb_oficina.setToolTipText("Oficina en la que trabaja el empleado");
        cb_oficina.setBounds(new java.awt.Rectangle(160, 100, 150, 26));
        cb_oficina.setMaximumSize(new java.awt.Dimension(150, 26));
        cb_oficina.setMinimumSize(new java.awt.Dimension(150, 26));
        cb_oficina.setPreferredSize(new java.awt.Dimension(100, 26));
        getContentPane().add(cb_oficina);
        cb_oficina.setBounds(160, 100, 150, 26);

        lblEadad.setLabelFor(spnEdad);
        lblEadad.setText("Edad: ");
        lblEadad.setToolTipText("edad del empelado");
        lblEadad.setBounds(new java.awt.Rectangle(40, 130, 40, 26));
        lblEadad.setMaximumSize(new java.awt.Dimension(40, 26));
        lblEadad.setMinimumSize(new java.awt.Dimension(40, 26));
        lblEadad.setOpaque(true);
        lblEadad.setPreferredSize(new java.awt.Dimension(40, 26));
        getContentPane().add(lblEadad);
        lblEadad.setBounds(40, 130, 40, 26);

        spnEdad.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));
        spnEdad.setToolTipText("Ingrese la edad del empleado");
        spnEdad.setBounds(new java.awt.Rectangle(160, 130, 80, 26));
        spnEdad.setMaximumSize(new java.awt.Dimension(80, 26));
        spnEdad.setMinimumSize(new java.awt.Dimension(80, 26));
        spnEdad.setPreferredSize(new java.awt.Dimension(80, 26));
        getContentPane().add(spnEdad);
        spnEdad.setBounds(160, 130, 80, 26);

        btnGPuesto.add(rbtn_Vendedor);
        rbtn_Vendedor.setText("Vendedor");
        rbtn_Vendedor.setBounds(new java.awt.Rectangle(40, 160, 91, 23));
        getContentPane().add(rbtn_Vendedor);
        rbtn_Vendedor.setBounds(40, 160, 91, 23);

        btnGPuesto.add(rbtn_gerente);
        rbtn_gerente.setText("Gerente");
        rbtn_gerente.setBounds(new java.awt.Rectangle(160, 160, 80, 23));
        rbtn_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_gerenteActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_gerente);
        rbtn_gerente.setBounds(160, 160, 80, 23);

        btnGPuesto.add(rbtn_director);
        rbtn_director.setText("Director");
        rbtn_director.setBounds(new java.awt.Rectangle(270, 160, 83, 23));
        getContentPane().add(rbtn_director);
        rbtn_director.setBounds(270, 160, 83, 23);

        lbl_fecha.setLabelFor(ftext_contratacion);
        lbl_fecha.setText("Fecha del contrato:");
        lbl_fecha.setBounds(new java.awt.Rectangle(40, 190, 120, 26));
        lbl_fecha.setMaximumSize(new java.awt.Dimension(120, 26));
        lbl_fecha.setMinimumSize(new java.awt.Dimension(120, 26));
        lbl_fecha.setPreferredSize(new java.awt.Dimension(120, 26));
        getContentPane().add(lbl_fecha);
        lbl_fecha.setBounds(40, 190, 120, 26);

        ftext_contratacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.FULL))));
        ftext_contratacion.setToolTipText("Fecha de contratacion...");
        ftext_contratacion.setBounds(new java.awt.Rectangle(160, 190, 150, 26));
        ftext_contratacion.setMaximumSize(new java.awt.Dimension(150, 26));
        ftext_contratacion.setMinimumSize(new java.awt.Dimension(150, 26));
        ftext_contratacion.setPreferredSize(new java.awt.Dimension(150, 26));
        getContentPane().add(ftext_contratacion);
        ftext_contratacion.setBounds(160, 190, 150, 26);

        jLabel1.setText("Jefe directo");
        jLabel1.setBounds(new java.awt.Rectangle(40, 230, 80, 26));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 230, 71, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ricardo Medina Martin ", "El Tuca Ferreti", " " }));
        jComboBox1.setBounds(new java.awt.Rectangle(160, 230, 120, 26));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 230, 200, 27);

        btn_archivo.setText("Archivo");

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.META_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        btn_archivo.add(salir);

        jMenuBar1.add(btn_archivo);

        btn_edicion.setText("Edición ");
        jMenuBar1.add(btn_edicion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        int dialogoButton = JOptionPane.showConfirmDialog(null, "¿Deseas salir?", "Alerta", JOptionPane.YES_NO_OPTION); 
        
        if(dialogoButton == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else{
            remove(dialogoButton); 
        }
    }//GEN-LAST:event_salirActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        //Metodo para que funcione el boton guardar 
        
        String nombre; 
        nombre = txtNombre.getText(); //Aqui se atrapa lo que se guardo...
        txtNombre.setText("");//Aqui se borra lo que habia en el input...
        System.out.println("Nombre del ampleado: " + nombre);
        //int numEmpleado = (int) sp_NEmpleado.getValue(); Aqui obtenemos todo el numero solamente, el numero... 
        int numEmpleado = (int) sp_NEmpleado.getValue(); 
        System.out.println("Numero de empleado:" + numEmpleado);
        
        if(cb_oficina.getSelectedIndex() != 0){
            /*System.out.println(cb_oficina.getSelectedIndex());
            System.out.println(cb_oficina.getSelectedItem());*/
            System.out.println("COOl");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No seleccionaste una oficina", "Error!", JOptionPane.ERROR_MESSAGE); 
            cb_oficina.setFocusable(true); 
            cb_oficina.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
            lblOficina.setBackground(Color.RED); 
        }
        
        int edadEmpleado = (int)spnEdad.getValue(); 
        String cargo = ""; 
        
        
        if(btnGPuesto.getSelection() != null){
            if(rbtn_director.isSelected())
                cargo = rbtn_director.getText();
            if(rbtn_Vendedor.isSelected())
                cargo = rbtn_Vendedor.getText();
            if(rbtn_gerente.isSelected())
                cargo = rbtn_gerente.getText();
            
            System.out.println(cargo);
        }
        else{
            rbtn_director.setBorder(javax.swing.BorderFactory.createEtchedBorder(Color.RED, null));
            rbtn_gerente.setBorder(javax.swing.BorderFactory.createEtchedBorder(Color.RED, null));
            rbtn_Vendedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(Color.RED, null));
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void rbtn_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_gerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGPuesto;
    private javax.swing.JMenu btn_archivo;
    private javax.swing.JMenu btn_edicion;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cb_oficina;
    private javax.swing.JFormattedTextField ftext_contratacion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEadad;
    private javax.swing.JLabel lblNEmpleado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOficina;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JRadioButton rbtn_Vendedor;
    private javax.swing.JRadioButton rbtn_director;
    private javax.swing.JRadioButton rbtn_gerente;
    private javax.swing.JMenuItem salir;
    private javax.swing.JSpinner sp_NEmpleado;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
