/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segundoParcial;

import javax.swing.JOptionPane;
import POO.Encuestado;
import com.jtattoo.plaf.AbstractLookAndFeel;
import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicLookAndFeel;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author ricardomedina
 */
public class Encuesta extends javax.swing.JFrame {
    
    //creamos nuestro objeto...
    Encuestado persona = new Encuestado();
    //variables de los dos unicos combo box... 
    String documento = null; 
    int[] full = new int[7];
    //documento...
    private static final String CSV_FILE_PATH = "encuesta.csv";
    //esta funcion valida si el array cuenta con puros unos o no...
    public static boolean validarArrayDeUnos(int[] array) {
        for (int i = 0; i < array.length; i++) {
            if (array[i] != 1) {
                return false; // Si se encuentra un valor distinto de 1, el array no cumple la condición
            }
        }
        return true; // Si todos los elementos del array son 1, se cumple la condición
    }
    //Esta funcion sirve para ingresar el correo en JOptionpane, seguira en el while hasta que el formato sea correcto...
    public static String ingresarCorreo() {
        String correo = JOptionPane.showInputDialog(null, "Ingrese su correo electrónico:");
        while (!validarCorreo(correo)) {
            JOptionPane.showMessageDialog(null, "Correo electrónico inválido. Intente nuevamente.");
            correo = JOptionPane.showInputDialog(null, "Ingrese su correo electrónico:");
        }
        return correo;
    }
    //Este valida si el formato de correo es correcto o no...
    public static boolean validarCorreo(String correo) {
        // Patrón de expresión regular para validar el correo electrónico
        String patron = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";    
        return correo.matches(patron);
    }
    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
        setLocationRelativeTo(null);  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        grupoBtnsGenero = new javax.swing.ButtonGroup();
        grupoBtnsEdoCivil = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        panel_azul = new javax.swing.JPanel();
        Jl_imagen = new javax.swing.JLabel();
        panel_dorado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Rb1Genero = new javax.swing.JRadioButton();
        Rb2Genero = new javax.swing.JRadioButton();
        Rb3Genero = new javax.swing.JRadioButton();
        PanelDivisorGustos = new javax.swing.JPanel();
        OtropanelAzul = new javax.swing.JPanel();
        lbl_genero = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_grado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_NomEscuela = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_civil = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_nacionalidad = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_gustos = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Cm_grado = new javax.swing.JComboBox<>();
        txt_nomEscuela = new javax.swing.JTextField();
        jr_soltero = new javax.swing.JRadioButton();
        jr_casado = new javax.swing.JRadioButton();
        jr_divorciado = new javax.swing.JRadioButton();
        jr_libre = new javax.swing.JRadioButton();
        jr_otro = new javax.swing.JRadioButton();
        jc_nacionalidad = new javax.swing.JComboBox<>();
        jC_cine = new javax.swing.JCheckBox();
        jC_musica = new javax.swing.JCheckBox();
        jC_comer = new javax.swing.JCheckBox();
        jC_fot = new javax.swing.JCheckBox();
        jC_lucha = new javax.swing.JCheckBox();
        jC_catar = new javax.swing.JCheckBox();
        jC_viajar = new javax.swing.JCheckBox();
        jC_asada = new javax.swing.JCheckBox();
        jC_programar = new javax.swing.JCheckBox();
        jC_leer = new javax.swing.JCheckBox();
        Btn_guardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        item_archivo = new javax.swing.JMenu();
        item_edicion = new javax.swing.JMenu();
        item_informacion = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encuesta ");
        setBounds(new java.awt.Rectangle(500, 50, 447, 750));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_azul.setBackground(new java.awt.Color(51, 153, 255));

        Jl_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_unedl-1.png"))); // NOI18N

        javax.swing.GroupLayout panel_azulLayout = new javax.swing.GroupLayout(panel_azul);
        panel_azul.setLayout(panel_azulLayout);
        panel_azulLayout.setHorizontalGroup(
            panel_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_azulLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(Jl_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panel_azulLayout.setVerticalGroup(
            panel_azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_azulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jl_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        background.add(panel_azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 140));

        panel_dorado.setBackground(new java.awt.Color(212, 215, 53));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Encuesta anual a la población ");
        jLabel1.setBounds(new java.awt.Rectangle(300, 0, 42, 17));

        javax.swing.GroupLayout panel_doradoLayout = new javax.swing.GroupLayout(panel_dorado);
        panel_dorado.setLayout(panel_doradoLayout);
        panel_doradoLayout.setHorizontalGroup(
            panel_doradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doradoLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        panel_doradoLayout.setVerticalGroup(
            panel_doradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_doradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(panel_dorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 40));

        grupoBtnsGenero.add(Rb1Genero);
        Rb1Genero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Rb1Genero.setText("Masculino");
        Rb1Genero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Rb1Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rb1GeneroActionPerformed(evt);
            }
        });
        background.add(Rb1Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, 20));

        grupoBtnsGenero.add(Rb2Genero);
        Rb2Genero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Rb2Genero.setText("Femenino");
        background.add(Rb2Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 90, -1));

        grupoBtnsGenero.add(Rb3Genero);
        Rb3Genero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Rb3Genero.setText("Otro");
        background.add(Rb3Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 60, -1));

        PanelDivisorGustos.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout PanelDivisorGustosLayout = new javax.swing.GroupLayout(PanelDivisorGustos);
        PanelDivisorGustos.setLayout(PanelDivisorGustosLayout);
        PanelDivisorGustosLayout.setHorizontalGroup(
            PanelDivisorGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        PanelDivisorGustosLayout.setVerticalGroup(
            PanelDivisorGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        background.add(PanelDivisorGustos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 450, 20));

        OtropanelAzul.setBackground(new java.awt.Color(51, 153, 255));

        lbl_genero.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_genero.setForeground(new java.awt.Color(255, 255, 255));
        lbl_genero.setText("Genero");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jSeparator1.setMaximumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));

        lbl_grado.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_grado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_grado.setText("Ultimo G. estudios");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jSeparator2.setMaximumSize(new java.awt.Dimension(50, 20));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));

        lbl_NomEscuela.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_NomEscuela.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NomEscuela.setText("Non. Escuela ");

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jSeparator3.setMaximumSize(new java.awt.Dimension(50, 20));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 20));

        lbl_civil.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_civil.setForeground(new java.awt.Color(255, 255, 255));
        lbl_civil.setText("Edo. Civil");

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jSeparator4.setMaximumSize(new java.awt.Dimension(50, 20));
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 20));

        lbl_nacionalidad.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_nacionalidad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nacionalidad.setText("Nacionalidad");

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jSeparator5.setMaximumSize(new java.awt.Dimension(50, 20));
        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 20));

        lbl_gustos.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_gustos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_gustos.setText("Gustos e intereses");

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jSeparator6.setMaximumSize(new java.awt.Dimension(50, 20));
        jSeparator6.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout OtropanelAzulLayout = new javax.swing.GroupLayout(OtropanelAzul);
        OtropanelAzul.setLayout(OtropanelAzulLayout);
        OtropanelAzulLayout.setHorizontalGroup(
            OtropanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtropanelAzulLayout.createSequentialGroup()
                .addGroup(OtropanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbl_genero))
                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_grado))
                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_gustos))
                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(OtropanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_NomEscuela)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(OtropanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_nacionalidad)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(OtropanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(OtropanelAzulLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lbl_civil)))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        OtropanelAzulLayout.setVerticalGroup(
            OtropanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtropanelAzulLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_grado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_NomEscuela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_civil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_nacionalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbl_gustos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        background.add(OtropanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 540));

        Cm_grado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Cm_grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ultimo Grado", "Primaria", "Secundaria", "Preparatoria ", "Universidad", "Maestria", "Doctorado" }));
        Cm_grado.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        Cm_grado.setMaximumSize(new java.awt.Dimension(130, 25));
        Cm_grado.setMinimumSize(new java.awt.Dimension(130, 25));
        Cm_grado.setPreferredSize(new java.awt.Dimension(130, 25));
        background.add(Cm_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        txt_nomEscuela.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_nomEscuela.setMaximumSize(new java.awt.Dimension(130, 25));
        txt_nomEscuela.setMinimumSize(new java.awt.Dimension(130, 25));
        txt_nomEscuela.setPreferredSize(new java.awt.Dimension(130, 25));
        background.add(txt_nomEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        grupoBtnsEdoCivil.add(jr_soltero);
        jr_soltero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jr_soltero.setText("Soltero");
        background.add(jr_soltero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        grupoBtnsEdoCivil.add(jr_casado);
        jr_casado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jr_casado.setText("Casado");
        background.add(jr_casado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        grupoBtnsEdoCivil.add(jr_divorciado);
        jr_divorciado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jr_divorciado.setText("Divorciado");
        background.add(jr_divorciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        grupoBtnsEdoCivil.add(jr_libre);
        jr_libre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jr_libre.setText("Union libre");
        background.add(jr_libre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        grupoBtnsEdoCivil.add(jr_otro);
        jr_otro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jr_otro.setText("Otro");
        background.add(jr_otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jc_nacionalidad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jc_nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacionalidad", "Mexicano ", "Extranjero" }));
        jc_nacionalidad.setMaximumSize(new java.awt.Dimension(130, 25));
        jc_nacionalidad.setMinimumSize(new java.awt.Dimension(130, 25));
        jc_nacionalidad.setPreferredSize(new java.awt.Dimension(130, 25));
        jc_nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_nacionalidadActionPerformed(evt);
            }
        });
        background.add(jc_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jC_cine.setText("Cine");
        background.add(jC_cine, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, -1));

        jC_musica.setText("Musica");
        background.add(jC_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jC_comer.setText("Comer");
        background.add(jC_comer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        jC_fot.setText("Fotbol");
        background.add(jC_fot, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jC_lucha.setText("Lucha libre");
        background.add(jC_lucha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, -1));

        jC_catar.setText("Catar cervezas");
        background.add(jC_catar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, -1, -1));

        jC_viajar.setText("Viajar");
        background.add(jC_viajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jC_asada.setText("Carne Asada");
        background.add(jC_asada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, -1, -1));

        jC_programar.setText("Programar");
        background.add(jC_programar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        jC_leer.setText("Leer");
        background.add(jC_leer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        Btn_guardar.setBackground(new java.awt.Color(51, 153, 255));
        Btn_guardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Btn_guardar.setText("Guardar");
        Btn_guardar.setBorder(null);
        Btn_guardar.setMaximumSize(new java.awt.Dimension(100, 30));
        Btn_guardar.setMinimumSize(new java.awt.Dimension(100, 30));
        Btn_guardar.setPreferredSize(new java.awt.Dimension(100, 30));
        Btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_guardarActionPerformed(evt);
            }
        });
        background.add(Btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, -1, -1));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setToolTipText("barra de menu");
        jMenuBar1.setMaximumSize(new java.awt.Dimension(212, 40));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(212, 40));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(212, 40));
        jMenuBar1.setSize(new java.awt.Dimension(75, 40));

        item_archivo.setText("Archivos");
        item_archivo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuBar1.add(item_archivo);

        item_edicion.setText("Edición");
        item_edicion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuBar1.add(item_edicion);

        item_informacion.setText("Información");
        item_informacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMenuBar1.add(item_informacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rb1GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rb1GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rb1GeneroActionPerformed

    
    //Aquí esta el codigo del combo box de nacionalidad...
    private void jc_nacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_nacionalidadActionPerformed
        String opcion = (String) jc_nacionalidad.getSelectedItem();
        
        
        if(opcion != null && opcion.equals("Extranjero")){
            boolean esDocumentoValido = false;
            String doc = null;
            String[] opcionesDocumentos = {"Pasaporte", "Visa de Trabajo", "Visa Humanitaria", "Visa H. Con Permiso de Trabajo", 
                "Residencia", "Visa de Estudiante"};
            while (!esDocumentoValido) {
                // Mostrar el cuadro de diálogo de entrada
                int documentoIngresado = JOptionPane.showOptionDialog(
                null,
                "Seleccione el tipo de documento:",
                "Información",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                opcionesDocumentos,
                opcionesDocumentos[0]);

                // Validar el documento ingresado
                switch (documentoIngresado) {
                case 0: doc = "Pasaporte"; break; 
                case 1: doc = "Visa de Trabajo"; break; 
                case 2: doc = "Visa Humanitaria"; break;
                case 3: doc = "Visa H. Con Permiso de Trabajo"; break;  
                case 4: doc = "Residencia"; break; 
                case 5: doc = "Visa de Estudiante"; break; 
                default: 
                    full[5] = 0;
                    esDocumentoValido = false;
                    JOptionPane.showMessageDialog(null, "Documento migratorio inválido. Intente nuevamente.");
                break;
                }
                if(documentoIngresado >= 0 && documentoIngresado <= 50){
                    esDocumentoValido = true; 
                    full[5] = 1; 
                }
            }
            documento = doc;
            persona.setEstadoMigratorio(documento);
        } 
        else{   
            full[5] = 1;
            persona.setEstadoMigratorio("Acta de nacimiento");
        }
    }//GEN-LAST:event_jc_nacionalidadActionPerformed

    private void Btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_guardarActionPerformed
        
        //Aquí iniciamos con genero...
        // Variable para almacenar la opción seleccionada
        String opcionGenero = null;

        // Verificar qué opción está seleccionada
        if (Rb1Genero.isSelected()) {
            opcionGenero = "Masculino";
        } 
        else if (Rb2Genero.isSelected()) {
            opcionGenero = "Femenino";
        } 
        else if (Rb3Genero.isSelected()) {
            opcionGenero = "Otro";
        }
        //mandamos la opcion al objeto...
        if(opcionGenero == null){
            full[0] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opción de genero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            persona.setGenero(opcionGenero);
            full[0] = 1;
        }
        //Terminamos el campo de genero... 
        
        //iniciamos con el campo de ultimo grado de estudios
        String last = null;
        int indexGrado = Cm_grado.getSelectedIndex();

        //Se lo mandamos al objeto... 
        if(indexGrado == 0){
            full[1] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opción de ultimo grado de estudios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            last = (String) Cm_grado.getSelectedItem();
            persona.setUltimoGrado(last);
            full[1] = 1;
        }
        //Aqui termina el campo de ultimo grado... 
        
        //Campo de nombre de la escual del ultimo grado de estudios...
        String escuela;
        escuela = txt_nomEscuela.getText();
        if(escuela.isEmpty()){
            full[2] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opción de escuela", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //enviamos la informacion al objeto... 
            persona.setNamEscuela(escuela);
            full[2] = 1;
        }
        
        //Campo de estado civil...  
        String opcionCivil = null;

        // Verificar qué opción está seleccionada
        if (jr_soltero.isSelected()) {
            opcionCivil = "Soltero";
        } 
        else if (jr_casado.isSelected()) {
            opcionCivil = "Casado";
        } 
        else if (jr_divorciado.isSelected()) {
            opcionCivil = "Divorciado";
        } 
        else if(jr_libre.isSelected()){
            opcionCivil = "Union libre";
        }
        else if(jr_otro.isSelected()){
            opcionCivil = "Otro";
        }
        
        if(opcionCivil == null){
            full[3] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opción de estado civil.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //mandamos la opcion al objeto...
            persona.setEstadoCivil(opcionCivil);
            full[3] = 1;
        }
        //Terminamos el campo de estado civil... 
        
        //Campo de nacionalidad...
        String nacionalidad = (String) jc_nacionalidad.getSelectedItem();
        int indexNacionalidad = jc_nacionalidad.getSelectedIndex();
        if(indexNacionalidad == 0){
            full[4] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun opción de nacionalidad.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Se lo mandamos al objeto... 
            persona.setNacionalidad(nacionalidad);
            full[4] = 1;
        }
        //Aqui termina el campo de nacionalidad... 
        
        //Aqui empezamos con los check boxes...
        boolean[] isSelected = new boolean[10];//En este array se guarda true o false... 
        String[] infoChecks = {"Cine", "Musica", "Fotbal", "Comer", "Viajar", "Leer", 
            "Lucha Libre", "Programar", "Catar Cerveza", "Carne Asada"};
        // Verificar si la casilla de verificación 1 está seleccionada
        isSelected[0] = jC_cine.isSelected();
        // Verificar si la casilla de verificación 2 está seleccionada
        isSelected[1] = jC_musica.isSelected();
        // Verificar si la casilla de verificación 3 está seleccionada
        isSelected[2] = jC_fot.isSelected();
        // Verificar si la casilla de verificación 1 está seleccionada
        isSelected[3] = jC_comer.isSelected();
        // Verificar si la casilla de verificación 2 está seleccionada
        isSelected[4] = jC_viajar.isSelected();
        // Verificar si la casilla de verificación 3 está seleccionada
        isSelected[5] = jC_leer.isSelected();
        // Verificar si la casilla de verificación 1 está seleccionada
        isSelected[6] = jC_lucha.isSelected();
        // Verificar si la casilla de verificación 2 está seleccionada
        isSelected[7] = jC_programar.isSelected();
        // Verificar si la casilla de verificación 3 está seleccionada
        isSelected[8] = jC_catar.isSelected();
        // Verificar si la casilla de verificación 3 está seleccionada
        isSelected[9] = jC_asada.isSelected();
        //En este for checaremos cuales son true y cuales false, dependiendo de la posicion... 
        String allChecks = null; 
        int y = 0; 
        for(int i = 0; i < 10; i++){
            if(isSelected[i] == true){
                y++; 
                if(y == 1){
                    allChecks = " - " + infoChecks[i] + " - "; 
                }
                else if(y > 1){
                    allChecks += infoChecks[i] + " - ";
                }
            }
        }
        
        if(allChecks == null){
            full[6] = 0;
            JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una opción.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //mandamos la info al campo correspondiente en el objeto... 
            persona.setIntereses(allChecks);
            full[6] = 1;
        }
        
        /*hay que validar que la información de todos los campos ya fue recolectada y que ningun String es null...*/
        boolean esValido = validarArrayDeUnos(full);
        
        if(esValido){
            String correo = ingresarCorreo();
            persona.setEmail(correo);
            //Aquí se estan imprimiendo en la terminal todas las opciones que se guardaron...
            String reg = persona.getGenero() + " , " + persona.getUltimoGrado() + " , " + persona.getNamEscuela() + " , " + persona.getEstadoCivil() + 
                    " , " + persona.getNacionalidad() + " , " + persona.getEstadoMigratorio() + " , " + persona.getIntereses() + " , " + 
                    persona.getEmail();
            System.out.println("Datos: " + reg);
            try {
                File file = new File(CSV_FILE_PATH);

                // Verificar si el archivo CSV ya existe
                boolean existeArchivo = file.exists();
                

                // Crear un FileWriter en modo de adición (append)
                FileWriter fileWriter = new FileWriter(file, true);
                PrintWriter writer = new PrintWriter(fileWriter);

                // Escribir el encabezado solo si el archivo no existe
                if (!existeArchivo) {
                    writer.println("Genero,Grado de estudio,Nom. Escuela,Estado Civil,Nacionalidad,Documento,Intereses, Email");
                }

                // Escribir la información en una nueva fila
                writer.println(reg);

                writer.close();

                System.out.println("La información se ha agregado al archivo encuestas.cvs");

            } 
            catch (IOException e) {
                System.out.println("Error al escribir en el archivo CSV: " + e.getMessage());
            }
            
            //Limpiamos todos los campos para que queden listos para volver a llenarlos...
            //genero...
            grupoBtnsGenero.clearSelection();
            //ultimo grados de estudios...
            Cm_grado.setSelectedIndex(0);
            //Nombre de escuela...
            txt_nomEscuela.setText("");
            //estado civil...
            grupoBtnsEdoCivil.clearSelection();
            //nacionalidad...
            jc_nacionalidad.setSelectedIndex(0);
            //gustos e intereses...
            jC_cine.setSelected(false);
            jC_musica.setSelected(false);
            jC_fot.setSelected(false);
            jC_comer.setSelected(false);
            jC_viajar.setSelected(false);
            jC_leer.setSelected(false);
            jC_lucha.setSelected(false);
            jC_programar.setSelected(false);
            jC_catar.setSelected(false);
            jC_asada.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "No se puede guardar hasta tener todos los datos recopilados.", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FastLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Encuesta.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_guardar;
    private javax.swing.JComboBox<String> Cm_grado;
    private javax.swing.JLabel Jl_imagen;
    private javax.swing.JPanel OtropanelAzul;
    private javax.swing.JPanel PanelDivisorGustos;
    private javax.swing.JRadioButton Rb1Genero;
    private javax.swing.JRadioButton Rb2Genero;
    private javax.swing.JRadioButton Rb3Genero;
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup grupoBtnsEdoCivil;
    private javax.swing.ButtonGroup grupoBtnsGenero;
    private javax.swing.JMenu item_archivo;
    private javax.swing.JMenu item_edicion;
    private javax.swing.JMenu item_informacion;
    private javax.swing.JCheckBox jC_asada;
    private javax.swing.JCheckBox jC_catar;
    private javax.swing.JCheckBox jC_cine;
    private javax.swing.JCheckBox jC_comer;
    private javax.swing.JCheckBox jC_fot;
    private javax.swing.JCheckBox jC_leer;
    private javax.swing.JCheckBox jC_lucha;
    private javax.swing.JCheckBox jC_musica;
    private javax.swing.JCheckBox jC_programar;
    private javax.swing.JCheckBox jC_viajar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JComboBox<String> jc_nacionalidad;
    private javax.swing.JRadioButton jr_casado;
    private javax.swing.JRadioButton jr_divorciado;
    private javax.swing.JRadioButton jr_libre;
    private javax.swing.JRadioButton jr_otro;
    private javax.swing.JRadioButton jr_soltero;
    private javax.swing.JLabel lbl_NomEscuela;
    private javax.swing.JLabel lbl_civil;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_grado;
    private javax.swing.JLabel lbl_gustos;
    private javax.swing.JLabel lbl_nacionalidad;
    private javax.swing.JPanel panel_azul;
    private javax.swing.JPanel panel_dorado;
    private javax.swing.JTextField txt_nomEscuela;
    // End of variables declaration//GEN-END:variables
}
