/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segundoParcial;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardomedina
 */
public class SegundoParcial extends javax.swing.JFrame {

    //objeto
    encuesta2 persona = new encuesta2();
    int[] full = new int[5];
    //documento...
    private static final String CSV_FILE_PATH = "segundoparcial.csv";
    //esta funcion valida si el array cuenta con puros unos o no...
    public static boolean validarArrayDeUnos(int[] array) {
        for (int i = 0; i < array.length; i++) {
            if (array[i] != 1) {
                return false; // Si se encuentra un valor distinto de 1, el array no cumple la condición
            }
        }
        return true; // Si todos los elementos del array son 1, se cumple la condición
    }
    
    public SegundoParcial() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    /*
    try {
                File file = new File(CSV_FILE_PATH);

                // Verificar si el archivo CSV ya existe
                boolean existeArchivo = file.exists();
                

                // Crear un FileWriter en modo de adición (append)
                FileWriter fileWriter = new FileWriter(file, true);
                PrintWriter writer = new PrintWriter(fileWriter);

                // Escribir el encabezado solo si el archivo no existe
                if (!existeArchivo) {
                    writer.println("Genero,Grado de estudio,Nom. Escuela,Estado Civil,Nacionalidad,Documento,Intereses, Email");
                }

                // Escribir la información en una nueva fila
                writer.println(reg);

                writer.close();

                System.out.println("La información se ha agregado al archivo encuestas.cvs");

            } 
            catch (IOException e) {
                System.out.println("Error al escribir en el archivo CSV: " + e.getMessage());
            }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbG_genero = new javax.swing.ButtonGroup();
        rbG_estadoCivil = new javax.swing.ButtonGroup();
        rbG_nacionalidad = new javax.swing.ButtonGroup();
        lblGenero = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        lblEstadoCivil = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        rb_casado = new javax.swing.JRadioButton();
        rb_soltero = new javax.swing.JRadioButton();
        rb_unionLibre = new javax.swing.JRadioButton();
        rb_divorciado = new javax.swing.JRadioButton();
        lblNacionalidad = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        rb_mexicano = new javax.swing.JRadioButton();
        rb_extranjero = new javax.swing.JRadioButton();
        lbl_lenguajesProgramacion = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jcp_c = new javax.swing.JCheckBox();
        jcp_cmas = new javax.swing.JCheckBox();
        jcp_php = new javax.swing.JCheckBox();
        jcp_java = new javax.swing.JCheckBox();
        jcp_otro = new javax.swing.JCheckBox();
        jci_frances = new javax.swing.JCheckBox();
        jci_ingles = new javax.swing.JCheckBox();
        jci_otro = new javax.swing.JCheckBox();
        jci_aleman = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_lenguajesp = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Examen Parcial #2");
        setBounds(new java.awt.Rectangle(0, 0, 600, 605));
        setMaximumSize(new java.awt.Dimension(600, 605));
        setMinimumSize(new java.awt.Dimension(600, 605));
        setPreferredSize(new java.awt.Dimension(600, 605));

        lblGenero.setText("Genero");

        rbG_genero.add(rbMasculino);
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        rbG_genero.add(rbFemenino);
        rbFemenino.setText("Femenino");

        lblEstadoCivil.setText("Estado Civil");

        rbG_estadoCivil.add(rb_casado);
        rb_casado.setText("Casado");

        rbG_estadoCivil.add(rb_soltero);
        rb_soltero.setText("Soltero");

        rbG_estadoCivil.add(rb_unionLibre);
        rb_unionLibre.setText("Union Libre");

        rbG_estadoCivil.add(rb_divorciado);
        rb_divorciado.setText("Divorciado");

        lblNacionalidad.setText("Nacionalidad");

        rbG_nacionalidad.add(rb_mexicano);
        rb_mexicano.setText("Mexicano");

        rbG_nacionalidad.add(rb_extranjero);
        rb_extranjero.setText("Extranjero");

        lbl_lenguajesProgramacion.setText("Lenguajes de programación");

        jLabel1.setText("Idiomas");

        jcp_c.setText("C#");

        jcp_cmas.setText("C++");

        jcp_php.setText("PHP");

        jcp_java.setText("JAVA");

        jcp_otro.setText("Otro");

        jci_frances.setText("Frances");

        jci_ingles.setText("Inglés");

        jci_otro.setText("Otro");

        jci_aleman.setText("Aleman");

        txt_lenguajesp.setColumns(20);
        txt_lenguajesp.setRows(5);
        txt_lenguajesp.setEnabled(false);
        jScrollPane1.setViewportView(txt_lenguajesp);

        jButton1.setText("Registrar");
        jButton1.setBounds(new java.awt.Rectangle(-32364, -32275, 90, 30));
        jButton1.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(90, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblGenero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoCivil)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMasculino)
                                .addGap(71, 71, 71)
                                .addComponent(rbFemenino))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNacionalidad)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_soltero)
                                .addGap(47, 47, 47)
                                .addComponent(rb_casado)
                                .addGap(37, 37, 37)
                                .addComponent(rb_unionLibre)
                                .addGap(41, 41, 41)
                                .addComponent(rb_divorciado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_mexicano)
                                .addGap(60, 60, 60)
                                .addComponent(rb_extranjero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_lenguajesProgramacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel1))
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcp_cmas)
                                    .addComponent(jcp_java)
                                    .addComponent(jcp_c))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcp_php)
                                    .addComponent(jcp_otro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(319, 319, 319)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jci_ingles)
                            .addComponent(jci_aleman)
                            .addComponent(jci_otro)
                            .addComponent(jci_frances))
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino))
                .addGap(30, 30, 30)
                .addComponent(lblEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_soltero)
                    .addComponent(rb_casado)
                    .addComponent(rb_unionLibre)
                    .addComponent(rb_divorciado))
                .addGap(18, 18, 18)
                .addComponent(lblNacionalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_mexicano)
                            .addComponent(rb_extranjero))
                        .addGap(30, 30, 30)
                        .addComponent(lbl_lenguajesProgramacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcp_cmas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcp_c)
                        .addGap(7, 7, 7)
                        .addComponent(jcp_java)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcp_php)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcp_otro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jci_ingles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jci_frances)
                        .addGap(7, 7, 7)
                        .addComponent(jci_aleman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jci_otro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       //Aquí iniciamos con genero...
        // Variable para almacenar la opción seleccionada
        String opcionGenero = null;

        // Verificar qué opción está seleccionada
        if (rbMasculino.isSelected()) {
            opcionGenero = "Masculino";
        } 
        else if (rbFemenino.isSelected()) {
            opcionGenero = "Femenino";
        } 
        //mandamos la opcion al objeto...
        if(opcionGenero == null){
            full[0] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opción de genero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            persona.setGenero(opcionGenero);
            full[0] = 1;
        }
        //Terminamos el campo de genero...  
        
        //Campo de estado civil...  
        String opcionCivil = null;

        // Verificar qué opción está seleccionada
        if (rb_soltero.isSelected()) {
            opcionCivil = "Soltero";
        } 
        else if (rb_casado.isSelected()) {
            opcionCivil = "Casado";
        } 
        else if (rb_unionLibre.isSelected()) {
            opcionCivil = "Union libre";
        } 
        else if(rb_divorciado.isSelected()){
            opcionCivil = "Divorciado";
        }
        
        if(opcionCivil == null){
            full[1] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opción de estado civil.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //mandamos la opcion al objeto...
            persona.setEstadoCivil(opcionCivil);
            full[1] = 1;
        }
        //Terminamos el campo de estado civil...
        
        //iniciamos con nacionalidad... 
        String nacionalidad = null;
        //verificamos... 
        if(rb_mexicano.isSelected()){
            nacionalidad = "Mexicano";
        }
        else if(rb_extranjero.isSelected()){
            nacionalidad = "Extranjero";
        }
        //verificamos que no este vacio... 
        if(nacionalidad == null){
            full[2] = 0;
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opción de nacionalidad.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            persona.setNacionalidad((nacionalidad));
            full[2] = 1;
        }
        //finalizamos con nacionalidad 
        
        //Aqui empezamos con los check boxes de lenguajes de programacion...
        boolean[] isSelectedP = new boolean[4];//En este array se guarda true o false... 
        String[] infoChecks = {"C++", "C#", "JAVA", "PHP"};
        // Verificar si la casilla de verificación 1 está seleccionada
        isSelectedP[0] = jcp_cmas.isSelected();
        // Verificar si la casilla de verificación 2 está seleccionada
        isSelectedP[1] = jcp_c.isSelected();
        // Verificar si la casilla de verificación 3 está seleccionada
        isSelectedP[2] = jcp_java.isSelected();
        // Verificar si la casilla de verificación 1 está seleccionada
        isSelectedP[3] = jcp_php.isSelected();
        //En este for checaremos cuales son true y cuales false, dependiendo de la posicion... 
        if(jcp_otro.isSelected()){
            txt_lenguajesp.setEnabled(true);
            String opcionesP = null; 
            opcionesP = txt_lenguajesp.getText();
            if(opcionesP == null){
                full[3] = 0;
                JOptionPane.showMessageDialog(null, "No se ha ingresado nada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                persona.setLenguajesP(opcionesP);
                full[3] = 1;
            }
        }
        else if(!jcp_otro.isSelected()){
            String allChecks = null; 
            int y = 0; 
            for(int i = 0; i < 4; i++){
                if(isSelectedP[i] == true){
                    y++; 
                    if(y == 1){
                        allChecks = " - " + infoChecks[i] + " - "; 
                    }
                    else if(y > 1){
                        allChecks += infoChecks[i] + " - ";
                    }
                }
            }
            if(allChecks == null){
                full[4] = 0;
                JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una opción.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                //mandamos la info al campo correspondiente en el objeto... 
                persona.setLenguajesP(allChecks);
                full[4] = 1;
            }
        }
        
        //iniciamos con el de idiomas... 
        //Aqui empezamos con los check boxes de lenguajes de programacion...
        boolean[] isSelectedI = new boolean[3];//En este array se guarda true o false... 
        String[] infoChecksi = {"Inglés", "Frances", "Aleman"};
        // Verificar si la casilla de verificación 1 está seleccionada
        isSelectedI[0] = jci_ingles.isSelected();
        // Verificar si la casilla de verificación 2 está seleccionada
        isSelectedI[1] = jci_frances.isSelected();
        // Verificar si la casilla de verificación 3 está seleccionada
        isSelectedI[2] = jci_aleman.isSelected();
        if(jci_otro.isSelected()){
            txt_lenguajesp.setText("");
            txt_lenguajesp.setEnabled(true);
            String opcionesI = null; 
            opcionesI = txt_lenguajesp.getText();
            if(opcionesI == null){
                full[5] = 0;
                JOptionPane.showMessageDialog(null, "No se ha ingresado nada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                persona.setIdiomas(opcionesI);
                full[5] = 1;
            }
        }
        else if(!jci_otro.isSelected()){
            String allChecksi = null; 
            int y = 0; 
            for(int i = 0; i < 3; i++){
                if(isSelectedI[i] == true){
                    y++; 
                    if(y == 1){
                        allChecksi = " - " + infoChecksi[i] + " - "; 
                    }
                    else if(y > 1){
                        allChecksi += infoChecksi[i] + " - ";
                    }
                }
            }
            if(allChecksi == null){
                full[5] = 0;
                JOptionPane.showMessageDialog(null, "Debe seleccionar por lo menos una opción.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                //mandamos la info al campo correspondiente en el objeto... 
                persona.setLenguajesP(allChecksi);
                full[5] = 1;
            }
        }
        
         /*hay que validar que la información de todos los campos ya fue recolectada y que ningun String es null...*/
        boolean esValido = validarArrayDeUnos(full);
        
        if(esValido){
            //persona.setFecha("14/06/2023");
            //Aquí se estan imprimiendo en la terminal todas las opciones que se guardaron...
            String reg = persona.getGenero() + " , " + persona.getEstadoCivil() + " , " + persona.getNacionalidad() + " , " + persona.getLenguajesP() + 
                    " , " + persona.getIdiomas();
            System.out.println("Datos: " + reg);
            try {
                File file = new File(CSV_FILE_PATH);

                // Verificar si el archivo CSV ya existe
                boolean existeArchivo = file.exists();
                

                // Crear un FileWriter en modo de adición (append)
                FileWriter fileWriter = new FileWriter(file, true);
                PrintWriter writer = new PrintWriter(fileWriter);

                // Escribir el encabezado solo si el archivo no existe
                if (!existeArchivo) {
                    writer.println("Genero,Estado civil,Nacionalidad,Lenguajes de programación,Idiomas");
                }

                // Escribir la información en una nueva fila
                writer.println(reg);

                writer.close();

                System.out.println("La información se ha agregado al archivo encuestas.cvs");

            } 
            catch (IOException e) {
                System.out.println("Error al escribir en el archivo CSV: " + e.getMessage());
            }
            
            //Limpiamos todos los campos para que queden listos para volver a llenarlos...
            //genero...
            rbG_genero.clearSelection();
            rbG_estadoCivil.clearSelection();
            rbG_nacionalidad.clearSelection();
            jcp_cmas.setSelected(false);
            jcp_c.setSelected(false);
            jcp_java.setSelected(false);
            jcp_php.setSelected(false);
            jcp_otro.setSelected(false);
            jci_ingles.setSelected(false);
            jci_frances.setSelected(false);
            jci_aleman.setSelected(false);
            jci_otro.setSelected(false);
            txt_lenguajesp.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "No se puede guardar hasta tener todos los datos recopilados.", "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundoParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundoParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundoParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundoParcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundoParcial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JCheckBox jci_aleman;
    private javax.swing.JCheckBox jci_frances;
    private javax.swing.JCheckBox jci_ingles;
    private javax.swing.JCheckBox jci_otro;
    private javax.swing.JCheckBox jcp_c;
    private javax.swing.JCheckBox jcp_cmas;
    private javax.swing.JCheckBox jcp_java;
    private javax.swing.JCheckBox jcp_otro;
    private javax.swing.JCheckBox jcp_php;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lbl_lenguajesProgramacion;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.ButtonGroup rbG_estadoCivil;
    private javax.swing.ButtonGroup rbG_genero;
    private javax.swing.ButtonGroup rbG_nacionalidad;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rb_casado;
    private javax.swing.JRadioButton rb_divorciado;
    private javax.swing.JRadioButton rb_extranjero;
    private javax.swing.JRadioButton rb_mexicano;
    private javax.swing.JRadioButton rb_soltero;
    private javax.swing.JRadioButton rb_unionLibre;
    private javax.swing.JTextArea txt_lenguajesp;
    // End of variables declaration//GEN-END:variables
}
