/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial3;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lidre
 */
public class Unicos extends javax.swing.JFrame {
JFileChooser jfile = new JFileChooser(); //librerira para abrir archivos de tu computadora
 File archivo;
    /**
     * Creates new form Unicos
     */
    public Unicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnicos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        BtnArchivo = new javax.swing.JMenu();
        BtnCargar = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnEdicion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("prcesar");
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));

        tblUnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Registro"
            }
        ));
        jScrollPane1.setViewportView(tblUnicos);

        BtnArchivo.setText("Archivo");

        BtnCargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BtnCargar.setText("Cargar");
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });
        BtnArchivo.add(BtnCargar);

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        BtnArchivo.add(btnSalir);

        jMenuBar1.add(BtnArchivo);

        btnEdicion.setText("Edicion ");
        jMenuBar1.add(btnEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed
       javax.swing.table.DefaultTableModel modeloTablaUnicos = new DefaultTableModel(new String[]{"numero","Registro"},2);
        // TODO add your handling code here:
        File unicosTxt;
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto plano","txt");//es la extension de los archivos a cargar 
        jfile.setFileFilter(filtro);//asigna el filtro a la variable jfile chooser
        int opcFile= jfile.showOpenDialog(this);
        System.out.println("Estado del archivo "+opcFile);
       
        if(opcFile!=JFileChooser.CANCEL_OPTION){//validamos que el usuario selecciono algo 
            unicosTxt = jfile.getSelectedFile(); //asignamos el archivo seleccionado 
            
            if(unicosTxt!=null || unicosTxt.getName().equals("")){//valida que sea diferente de 
                
                if(unicosTxt.getAbsolutePath().endsWith("txt")){//obtener la ruta de llegar al archivo dentro de la comnputadora 
                    //endswith es la terminacion del archivo 
                    try{
                        BufferedReader buffer = new BufferedReader(new FileReader(unicosTxt));
                        String cad=buffer.readLine();
                        int contador=1;
                       
                        while(cad!=null){// lee una linea de el archivo 
                            System.out.println(cad);// imprime la linea 
                           String registro [] = new String []{""+contador,cad};
                            modeloTablaUnicos.addRow(registro); //nos define que insertar en cada renglon                            contador++;
                            contador++; 
                            cad=buffer.readLine();
                            
                            //cad = buffer.readLine();// vuelve a leer la linea hasta que llegue al final 
                        }
                        tblUnicos.setModel(modeloTablaUnicos);// se agrega al modelo completo a la tabla con la informacion
                    }catch(Exception e){
                        
                    }
                }else{
                  JOptionPane.showMessageDialog(rootPane,"debes seleccionar un archivo valido","Error",JOptionPane.ERROR_MESSAGE);   
                }
            }else{
              JOptionPane.showMessageDialog(rootPane,"debes seleccionar un archivo valido","Error",JOptionPane.ERROR_MESSAGE);  
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"debes seleccionar un archivo de texto plano","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_BtnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BtnArchivo;
    private javax.swing.JMenuItem BtnCargar;
    private javax.swing.JMenu btnEdicion;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUnicos;
    // End of variables declaration//GEN-END:variables
}
