/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TercerParcial;

import javax.swing.JOptionPane;

/**
 *
 * @author ricardomedina
 */
public class ProgressBar extends javax.swing.JFrame {

    /**
     * Creates new form BarraProgreso
     */
    public ProgressBar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraProgreso = new javax.swing.JProgressBar();
        lblPorcentaje = new javax.swing.JLabel();
        sldControlBarra = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        btnReload = new javax.swing.JMenuItem();
        btnEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Progress bar");
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        BarraProgreso.setToolTipText("Barra de Progreso");
        getContentPane().add(BarraProgreso);
        BarraProgreso.setBounds(110, 150, 146, 4);

        lblPorcentaje.setText("0%");
        getContentPane().add(lblPorcentaje);
        lblPorcentaje.setBounds(300, 150, 50, 17);

        sldControlBarra.setMinorTickSpacing(1);
        sldControlBarra.setPaintLabels(true);
        sldControlBarra.setPaintTicks(true);
        sldControlBarra.setToolTipText("control de barra");
        sldControlBarra.setValue(0);
        sldControlBarra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldControlBarraStateChanged(evt);
            }
        });
        getContentPane().add(sldControlBarra);
        sldControlBarra.setBounds(90, 100, 200, 28);

        btnArchivo.setText("Archivo");

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnSalir.setText("Out");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnArchivo.add(btnSalir);

        btnReload.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        btnArchivo.add(btnReload);

        jMenuBar1.add(btnArchivo);

        btnEditar.setText("Editar");
        jMenuBar1.add(btnEditar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JOptionPane.showMessageDialog(rootPane, "quieres salir");
        System.exit(0);
        
    
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReloadActionPerformed

    private void sldControlBarraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldControlBarraStateChanged
        int progreso = sldControlBarra.getValue();
        lblPorcentaje.setText(progreso+"%");
        BarraProgreso.setValue(progreso);
    }//GEN-LAST:event_sldControlBarraStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgressBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgreso;
    private javax.swing.JMenu btnArchivo;
    private javax.swing.JMenu btnEditar;
    private javax.swing.JMenuItem btnReload;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JSlider sldControlBarra;
    // End of variables declaration//GEN-END:variables
}
