/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TercerParcial;

import java.time.LocalDate;//biblioteca para tomar el mes y el año...
import java.util.Random;//para generar numeros randome...
import javax.swing.JOptionPane;

/**
 *
 * @author ricardomedina
 */
public class RegistroAlumnos extends javax.swing.JFrame {
   
    //variables global...
    String ID;
    String reg; 

    public RegistroAlumnos() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /*El siguiente metodo lo cree especificamente para generar el ID del alumno...
    1. Genera 3 numeros randome... 
    2. Toma las iniciales del nombre y apellidos...
    3. Dependiendo del mes le agrega el A o B (por calendario A o B)
    4. Por ultimo le agrega los dos ultimos numeros del año en que se registro...*/
    public static String generarAlumnoID(String nombre, String apellidoPaterno, String apellidoMaterno) {
        // Generar tres números aleatorios del 0 al 9
        Random random = new Random();
        int num1 = random.nextInt(10);
        int num2 = random.nextInt(10);
        int num3 = random.nextInt(10);

        // Obtener las iniciales del nombre y apellidos
        char inicialNombre = Character.toUpperCase(nombre.charAt(0));
        char inicialApellidoPaterno = Character.toUpperCase(apellidoPaterno.charAt(0));
        char inicialApellidoMaterno = Character.toUpperCase(apellidoMaterno.charAt(0));

        // Obtener el calendario de registro según el mes actual
        LocalDate fechaActual = LocalDate.now();
        int mesActual = fechaActual.getMonthValue();
        char calendario = (mesActual >= 1 && mesActual <= 8) ? 'B' : 'A';

        // Obtener los dos últimos dígitos del año actual
        int anioActual = fechaActual.getYear();
        int ultimosDosDigitosAnio = anioActual % 100;

        // Construir el ID del alumno
        String alumnoID = String.format("%d%d%d%s%s%s%s%d", num1, num2, num3, inicialNombre,
                inicialApellidoPaterno, inicialApellidoMaterno, calendario, ultimosDosDigitosAnio);

        return alumnoID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_id = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_Apaterno = new javax.swing.JLabel();
        jl_edad = new javax.swing.JLabel();
        jl_Amaterno = new javax.swing.JLabel();
        jl_licenciatura = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_Apaterno = new javax.swing.JTextField();
        txt_Amaterno = new javax.swing.JTextField();
        jp_edad = new javax.swing.JSpinner();
        jc_licenciatura = new javax.swing.JComboBox<>();
        btn_id = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro alumnos");
        setBounds(new java.awt.Rectangle(0, 0, 500, 630));
        setMaximumSize(new java.awt.Dimension(500, 630));
        setMinimumSize(new java.awt.Dimension(500, 630));
        setPreferredSize(new java.awt.Dimension(500, 630));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos del alumno");
        jLabel1.setBounds(new java.awt.Rectangle(0, 0, 42, 17));

        jl_id.setText("ID:  ");
        jl_id.setBounds(new java.awt.Rectangle(0, 0, 42, 17));

        jl_nombre.setText("Nombre: ");

        jl_Apaterno.setText("Apellido paterno: ");

        jl_edad.setText("Edad: ");

        jl_Amaterno.setText("Apellido materno: ");

        jl_licenciatura.setText("Licenciatura: ");

        jButton1.setText("Registrar");
        jButton1.setBounds(new java.awt.Rectangle(0, 0, 100, 30));
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jp_edad.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));
        jp_edad.setBounds(new java.awt.Rectangle(0, 0, 64, 23));

        jc_licenciatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Software", "Leyes", "Contaduría Pública", "Contaduría Pública y Auditoría", "Administración de Empresas", "Finanzas", "Ciencias de la Comunicación", "Gastronomía", "Psicología", "Diseño Gráfico", " " }));
        jc_licenciatura.setBounds(new java.awt.Rectangle(0, 0, 72, 23));

        btn_id.setText("Generar ID");
        btn_id.setBounds(new java.awt.Rectangle(0, 0, 78, 23));
        btn_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_id, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_Apaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_Amaterno))
                            .addComponent(jl_edad)
                            .addComponent(jl_licenciatura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Amaterno)
                                .addComponent(txt_Apaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jc_licenciatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_nombre))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Apaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Apaterno))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Amaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Amaterno))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_edad)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_licenciatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_licenciatura))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_id)
                    .addComponent(jl_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idActionPerformed
        
        String nombre = txt_nombre.getText(); 
        String apellidoPa = txt_Apaterno.getText();
        String apellidoMa = txt_Amaterno.getText();
        
        if(nombre == "" || apellidoPa == "" || apellidoMa == ""){
            
        }
        else{
            ID = generarAlumnoID(nombre, apellidoPa, apellidoMa);
            jl_id.setText("ID: " + ID);
        }
    }//GEN-LAST:event_btn_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        Tabla1 tabla = new Tabla1();
        
        //Primero resepcionamos el nombre... 
        String nombre = txt_nombre.getText();
        if(nombre == ""){
            //mensaje de vacio...
        }
        
        //recepcionamos apellido paterno...
        String apellidoPa = txt_Apaterno.getText();
        if(apellidoPa == ""){
            
        }
        //recepcionamos apellido materno...
        String apellidoMa = txt_Amaterno.getText(); 
        if(apellidoMa == ""){
            
        }
        //recepcionamos la edad...
        int edad = 0;
        edad = (int) jp_edad.getValue();
        if(edad == 0){
            
        }
        //recepcionamos la licenciatura...
        String lic = (String) jc_licenciatura.getSelectedItem();
        
        reg = nombre + " | " + apellidoPa + " | " + apellidoMa + " | " + edad + " | " + lic + " | " + ID;
        
        tabla.getDato(ID, apellidoPa, apellidoMa, edad, lic);
        
        //limpiamos todos los campos...
        txt_nombre.setText("");
        txt_Apaterno.setText("");
        txt_Amaterno.setText("");
        jp_edad.setValue(18);
        jc_licenciatura.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jc_licenciatura;
    private javax.swing.JLabel jl_Amaterno;
    private javax.swing.JLabel jl_Apaterno;
    private javax.swing.JLabel jl_edad;
    private javax.swing.JLabel jl_id;
    private javax.swing.JLabel jl_licenciatura;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JSpinner jp_edad;
    private javax.swing.JTextField txt_Amaterno;
    private javax.swing.JTextField txt_Apaterno;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
