package TercerParcial;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ricardomedina
 */
public class Tabla1 extends javax.swing.JFrame {
    
    //Aqui tenemos nuestra tabla de alumnos...
    RegistroAlumnos newTable = new RegistroAlumnos();
    private String n; 
    private String pa; 
    private String ma; 
    private int edad; 
    private String lic; 
    
    public Tabla1() {
        initComponents();
        setLocationRelativeTo(null);
    }
        
    
    public void getDato(String n, String a, String ma, int edad, String lic){
        this.n = n; 
        this.pa = a; 
        this.ma = ma; 
        this.edad = edad; 
        this.lic = lic;
        
        String ed = String.valueOf(edad);
        System.out.println("Datos de la segunda tabla: " + n + " - " + pa + " - "  + ma+ " - "  + edad+ " - "  + lic);
        javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"ID",
            "Nombre","A paterno","A materno","Edad","Licenciatura"}, 0);
        String fila [] = new String []{"" + n, pa, ma, ed, lic};
        modeloTablaUnicos.addRow(fila);
        jt_registrados.setModel(modeloTablaUnicos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_registrados = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jm_salir = new javax.swing.JMenuItem();
        jm_nuevo = new javax.swing.JMenuItem();
        jm_edicion = new javax.swing.JMenu();
        jm_insertar = new javax.swing.JMenuItem();
        jm_eliminar = new javax.swing.JMenuItem();
        jm_modificar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información de alumnos registrados");
        setBounds(new java.awt.Rectangle(0, 0, 550, 500));
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(550, 500));
        setPreferredSize(new java.awt.Dimension(550, 500));

        jt_registrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "A paterno", "A materno", "Edad", "Licenciatura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_registrados);

        jm_archivo.setText("Archivo");

        jm_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_DOWN_MASK));
        jm_salir.setText("Salir");
        jm_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_salirActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_salir);

        jm_nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.META_DOWN_MASK));
        jm_nuevo.setText("Nuevo Registro");
        jm_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_nuevoActionPerformed(evt);
            }
        });
        jm_archivo.add(jm_nuevo);

        jMenuBar1.add(jm_archivo);

        jm_edicion.setText("Edición");

        jm_insertar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.META_DOWN_MASK));
        jm_insertar.setText("Insertar");
        jm_edicion.add(jm_insertar);

        jm_eliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.META_DOWN_MASK));
        jm_eliminar.setText("Eliminar");
        jm_edicion.add(jm_eliminar);

        jm_modificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.META_DOWN_MASK));
        jm_modificar.setText("Modificar");
        jm_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_modificarActionPerformed(evt);
            }
        });
        jm_edicion.add(jm_modificar);

        jMenuBar1.add(jm_edicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_nuevoActionPerformed
        //Aqui en este apartado es donde daremos la accion de abrir otro frame para que ahi se haga un registro y 
        //posteriormente la informacion sea mandada aqui para ser mostrada en la tabla...
        newTable.setLocationByPlatform(true);
        newTable.setBounds(0, 0, 500, 630);
        newTable.setSize(500, 630); 
        newTable.setVisible(true);
        newTable.setLocationRelativeTo(null);
    }//GEN-LAST:event_jm_nuevoActionPerformed

    private void jm_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_modificarActionPerformed

    private void jm_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_salirActionPerformed
        //codigo muy complejo para salir del frame... XD 
        int dialogoButton = JOptionPane.showConfirmDialog(null, "¿Deseas salir?", "Alerta", JOptionPane.YES_NO_OPTION);
        
        if(dialogoButton == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else{
            remove(dialogoButton); 
        }
    }//GEN-LAST:event_jm_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jm_archivo;
    private javax.swing.JMenu jm_edicion;
    private javax.swing.JMenuItem jm_eliminar;
    private javax.swing.JMenuItem jm_insertar;
    private javax.swing.JMenuItem jm_modificar;
    private javax.swing.JMenuItem jm_nuevo;
    private javax.swing.JMenuItem jm_salir;
    private javax.swing.JTable jt_registrados;
    // End of variables declaration//GEN-END:variables
}
