package TercerParcial;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import metodosUnicos.MetodosUnicos;
import metodosUnicos.Ordenamientos;
import metodosUnicos.busquedas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ricardomedina
 */
public class Unicos extends javax.swing.JFrame {

    JFileChooser jfile = new JFileChooser(); //esta instanciado...
    int opcFile;
    File archivo; //declarado sin instanciar...
    String[] forAwhile = new String[1221];
    String[] forAwhileInverso = new String[1221]; 
    String[] OrdenDefault = new String[1221]; //Aqui en esta array tenemos ya ordenado los datos de la primera caraga...
    String type;
    /*esta variable se encargara de optener un valor booleano el cual sera usado para validar si se ha ordenado los datos o no
    ya que la busqueda booleana no puede servir sin tener datos ordenados...*/
    boolean orden = false; //por defecto es false porque no se ha usado...
    public Unicos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        btn_reset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivos = new javax.swing.JMenu();
        j_salir = new javax.swing.JMenuItem();
        j_cargar = new javax.swing.JMenuItem();
        jmEstructrura = new javax.swing.JMenu();
        j_e1a = new javax.swing.JMenuItem();
        j_e1b = new javax.swing.JMenuItem();
        j_e1c = new javax.swing.JMenuItem();
        je2 = new javax.swing.JMenuItem();
        jmOrdennamiento = new javax.swing.JMenu();
        orden_shell = new javax.swing.JMenuItem();
        orden_burbuja = new javax.swing.JMenuItem();
        orden_seleccion = new javax.swing.JMenuItem();
        jmBusquedas = new javax.swing.JMenu();
        busqueda_binaria = new javax.swing.JMenuItem();
        busqueda_secuencial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 695, 650));
        setMinimumSize(new java.awt.Dimension(695, 650));

        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Registro"
            }
        ));
        jScrollPane1.setViewportView(tabla_datos);

        btn_reset.setText("Reset");
        btn_reset.setBounds(new java.awt.Rectangle(0, 0, 100, 30));
        btn_reset.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_reset.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_reset.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jmArchivos.setText("Archivo");

        j_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_DOWN_MASK));
        j_salir.setText("Salir");
        j_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_salirActionPerformed(evt);
            }
        });
        jmArchivos.add(j_salir);

        j_cargar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.META_DOWN_MASK));
        j_cargar.setText("Cargar");
        j_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_cargarActionPerformed(evt);
            }
        });
        jmArchivos.add(j_cargar);

        jMenuBar1.add(jmArchivos);

        jmEstructrura.setText("Estructuras");

        j_e1a.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.META_DOWN_MASK));
        j_e1a.setText("E1a");
        j_e1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_e1aActionPerformed(evt);
            }
        });
        jmEstructrura.add(j_e1a);

        j_e1b.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.META_DOWN_MASK));
        j_e1b.setText("E1b");
        j_e1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_e1bActionPerformed(evt);
            }
        });
        jmEstructrura.add(j_e1b);

        j_e1c.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.META_DOWN_MASK));
        j_e1c.setText("E1c");
        j_e1c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_e1cActionPerformed(evt);
            }
        });
        jmEstructrura.add(j_e1c);

        je2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.META_DOWN_MASK));
        je2.setText("E2");
        je2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                je2ActionPerformed(evt);
            }
        });
        jmEstructrura.add(je2);

        jMenuBar1.add(jmEstructrura);

        jmOrdennamiento.setText("Ordenamientos");

        orden_shell.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        orden_shell.setText("Shell");
        orden_shell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orden_shellActionPerformed(evt);
            }
        });
        jmOrdennamiento.add(orden_shell);

        orden_burbuja.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        orden_burbuja.setText("Burbuja");
        orden_burbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orden_burbujaActionPerformed(evt);
            }
        });
        jmOrdennamiento.add(orden_burbuja);

        orden_seleccion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        orden_seleccion.setText("Seleccion");
        orden_seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orden_seleccionActionPerformed(evt);
            }
        });
        jmOrdennamiento.add(orden_seleccion);

        jMenuBar1.add(jmOrdennamiento);

        jmBusquedas.setText("Busquedas");

        busqueda_binaria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        busqueda_binaria.setText("Binaria");
        busqueda_binaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_binariaActionPerformed(evt);
            }
        });
        jmBusquedas.add(busqueda_binaria);

        busqueda_secuencial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        busqueda_secuencial.setText("Secuencial");
        busqueda_secuencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqueda_secuencialActionPerformed(evt);
            }
        });
        jmBusquedas.add(busqueda_secuencial);

        jMenuBar1.add(jmBusquedas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_salirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "¿Deseas salir del programa?", "Confirmación", JOptionPane.YES_NO_OPTION);
         
        if(opcion == JOptionPane.YES_OPTION){
            System.exit(0); 
        }
         
    }//GEN-LAST:event_j_salirActionPerformed

    private void j_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_cargarActionPerformed
        //Aqui tenemos el metodo principal para cargar todo...
        javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
        
        //si cargamos un valor por primeras vez o cuantas veces sea, el valor de la variable orden tiene que ser false ya que se 
        //carga todo sin estar ordenado...
        orden = false; 
        //se cargara un archivo...
        //variable de tipo archivo... 
        File unicosTxt; 
        //Filtramos los archivos, ponemos solos los que seran permitidos...
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("", "csv", "xls", "xlsx", "txt");
        //Se realiza la validacion del filtro... 
        jfile.setFileFilter(filtro);
        opcFile = jfile.showOpenDialog(this); 
        type = "Carga";
        System.out.println("Estado del archivo: " + opcFile);
        if(opcFile != JFileChooser.CANCEL_OPTION){
            unicosTxt = jfile.getSelectedFile(); 
            if(unicosTxt != null || unicosTxt.getName().equals("")){
                if(unicosTxt.getAbsolutePath().endsWith(".txt")){//regresa un boolenao el endsWith
                    try{
                        BufferedReader buffer = new BufferedReader(new FileReader(unicosTxt));
                        //lo lee una vez para que la variable no paresca estar null...
                        String cad = buffer.readLine(); 
                        int contador = 0;
                        int i = 1;
                        while(cad != null){
                            //cuando ya la leyo una vez se detecta que no es nula y despues
                            //sigue leyendo la siguiente y la siguiente linea hasta que
                            //llegar a la ultima linera, ya que lo siguiente seria que 
                            //automaticamente la cadena vuelve a ser null y para el while...
                            System.out.println(cad);
                            OrdenDefault[contador] = cad; 
                            forAwhileInverso[contador] = cad; 
                            forAwhile[contador] = cad;
                            
                            String registro [] = new String []{"" + i, cad}; 
                            modeloTablaUnicos.addRow(registro);
                            contador++;
                            i++;
                            cad = buffer.readLine();
                        }
                        tabla_datos.setModel(modeloTablaUnicos); 
                        forAwhileInverso = Ordenamientos.ordenamientoBurbuja(forAwhileInverso); 
                        OrdenDefault = Ordenamientos.ordenamientoBurbuja(OrdenDefault); 
                    }
                    catch(Exception e){
                        
                    }
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un archivo de texto plano", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un archivo de texto plano", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar un archivo de texto plano", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_j_cargarActionPerformed

    private void j_e1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_e1bActionPerformed
        if(jfile.getSelectedFile() != null){
            type = "E1b";
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            //Variable tipo file...
            File unicosTxt;
            //le pasamos el archivo que tiene jfile...
            unicosTxt = jfile.getSelectedFile();
            //Se selecciono un archivo...
            try{
                //lo lee una vez para que la variable no paresca estar null...
                String cad; 
                String[] estructura = MetodosUnicos.E1b(unicosTxt); 
                int contador = 0; 
                int i = 1;
                do{
                    cad = estructura[contador];
                    forAwhile[contador] = cad;
                    forAwhileInverso[contador] = cad; 

                    String registro [] = new String []{"E1b: " + i, cad};
                    modeloTablaUnicos.addRow(registro);
                    contador++;
                    i++;
                }while(contador < estructura.length);
                forAwhileInverso = Ordenamientos.ordenamientoBurbuja(forAwhileInverso); 
                tabla_datos.setModel(modeloTablaUnicos);
            }
            catch(IOException e){
                System.out.println("Error");
            }
        }else{
            //No se selecciono nada...
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado anteriormente", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_j_e1bActionPerformed

    private void je2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_je2ActionPerformed
        if(jfile.getSelectedFile() != null){
            type = "E2";
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            //Variable tipo file...
            File unicosTxt;
            //le pasamos el archivo que tiene jfile...
            unicosTxt = jfile.getSelectedFile();
            //Se selecciono un archivo...
            try{
                //lo lee una vez para que la variable no paresca estar null...
                String cad; 
                String[] estructura = MetodosUnicos.E2(unicosTxt); 
                int contador = 0; 
                int i = 1;
                do{
                    cad = estructura[contador];
                    forAwhile[contador] = cad;
                    forAwhileInverso[contador] = cad; 

                    String registro [] = new String []{"E2: " + i, cad};
                    modeloTablaUnicos.addRow(registro);
                    contador++;
                    i++;
                }while(contador < estructura.length);
                forAwhileInverso = Ordenamientos.ordenamientoBurbuja(forAwhileInverso); 
                tabla_datos.setModel(modeloTablaUnicos);
            }
            catch(IOException e){
                System.out.println("Error");
            }
        }else{
            //No se selecciono nada...
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado anteriormente", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_je2ActionPerformed

    private void orden_shellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orden_shellActionPerformed
        //Primer hay que validar que haya algun archivo seleccionado...
        if(jfile.getSelectedFile() != null){
            //validamos que si se ha ordenado...
            orden = true; 
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            
            //lo lee una vez para que la variable no paresca estar null...
            String cad; 
            String[] estructura = Ordenamientos.ordenamientoSehll(forAwhile);
            int contador = 0; 
            int i = 1; 
            do{
                cad = estructura[contador];

                String registro [] = new String []{ type + " Sehll: " + i, cad}; 
                modeloTablaUnicos.addRow(registro);
                contador++;
                i++;
            }while(contador < estructura.length);
            tabla_datos.setModel(modeloTablaUnicos);
        }else{
            //No se selecciono nada...
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado anteriormente", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_orden_shellActionPerformed

    private void orden_burbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orden_burbujaActionPerformed
        if(jfile.getSelectedFile() != null){
            //validamos que si se ha ordenado...
            orden = true; 
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            
            //lo lee una vez para que la variable no paresca estar null...
            String cad; 
            String[] estructura = Ordenamientos.ordenamientoBurbuja(forAwhile);
            int contador = 0; 
            int i = 1; 
            do{
                cad = estructura[contador];

                String registro [] = new String []{ type + " Burbuja: " + i, cad}; 
                modeloTablaUnicos.addRow(registro);
                contador++;
                i++;
            }while(contador < estructura.length);
            tabla_datos.setModel(modeloTablaUnicos);
        }else{
            //No se selecciono nada...
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado anteriormente", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_orden_burbujaActionPerformed

    private void busqueda_binariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_binariaActionPerformed
        //primero hay que validar que los datos si esten validados...
        if(orden == true && jfile.getSelectedFile() != null){
            
            String cadena = null; //tomamos la informacion aqui y despues la imprimiremos en algo por definir aun...
            String input = null;
            
            
            input = JOptionPane.showInputDialog(null, "Ingrese el CRN");

            cadena = busquedas.binarySearch(OrdenDefault, input);
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            int e = 1; 
            if(cadena != "no"){
                String registro [] = new String []{ type + " Selección: " + e, cadena}; 
                modeloTablaUnicos.addRow(registro);
                tabla_datos.setModel(modeloTablaUnicos);
            }else{
                cadena = "No se encontro el dato requerido."; 
                String registro [] = new String []{"Busqueda binaria: " + e, cadena}; 
                modeloTablaUnicos.addRow(registro);
                tabla_datos.setModel(modeloTablaUnicos);
            }
        } 
        else if(jfile.getSelectedFile() == null){
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo cargado", 
                        "Error", JOptionPane.WARNING_MESSAGE);
        }
        else if(orden == false && jfile.getSelectedFile() != null){
            JOptionPane.showMessageDialog(rootPane, "Los datos aun no estan ordenados.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_busqueda_binariaActionPerformed

    private void j_e1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_e1aActionPerformed
        if(jfile.getSelectedFile() != null){
            type = "E1a";
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            //Variable tipo file...
            File unicosTxt;
            //le pasamos el archivo que tiene jfile...
            unicosTxt = jfile.getSelectedFile();
            //Se selecciono un archivo...
            try{
                //lo lee una vez para que la variable no paresca estar null...
                String cad; 
                String[] estructura = MetodosUnicos.E1a(unicosTxt); 
                int contador = 0; 
                int i = 1;
                do{
                    cad = estructura[contador];
                    forAwhile[contador] = cad;
                    forAwhileInverso[contador] = cad; 

                    String registro [] = new String []{"E1a: " + i, cad};
                    modeloTablaUnicos.addRow(registro);
                    contador++;
                    i++;
                }while(contador < estructura.length);
                forAwhileInverso = Ordenamientos.ordenamientoBurbuja(forAwhileInverso); 
                tabla_datos.setModel(modeloTablaUnicos);
            }
            catch(IOException e){
                System.out.println("Error");
            }
        }else{
            //No se selecciono nada...
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado anteriormente", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_j_e1aActionPerformed

    private void j_e1cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_e1cActionPerformed
        if(jfile.getSelectedFile() != null){
            type = "E1c";
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            //Variable tipo file...
            File unicosTxt;
            //le pasamos el archivo que tiene jfile...
            unicosTxt = jfile.getSelectedFile();
            //Se selecciono un archivo...
            try{
                //lo lee una vez para que la variable no paresca estar null...
                String cad; 
                String[] estructura = MetodosUnicos.E1c(unicosTxt); 
                int contador = 0; 
                int i = 1;
                do{
                    cad = estructura[contador];
                    forAwhile[contador] = cad;
                    forAwhileInverso[contador] = cad; 

                    String registro [] = new String []{"E1c: " + i, cad};
                    modeloTablaUnicos.addRow(registro);
                    contador++;
                    i++;
                }while(contador < estructura.length);
                forAwhileInverso = Ordenamientos.ordenamientoBurbuja(forAwhileInverso); 
                tabla_datos.setModel(modeloTablaUnicos);
            }
            catch(IOException e){
                System.out.println("Error");
            }
        }else{
            //No se selecciono nada...
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado anteriormente", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_j_e1cActionPerformed

    private void orden_seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orden_seleccionActionPerformed
        if(jfile.getSelectedFile() != null){
            //validamos que si se ha ordenado...
            orden = true; 
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            
            //lo lee una vez para que la variable no paresca estar null...
            String cad; 
            String[] estructura = Ordenamientos.ordenamientoSeleccion(forAwhile);
            int contador = 0; 
            int i = 1; 
            do{
                cad = estructura[contador];

                String registro [] = new String []{ type + " Selección: " + i, cad}; 
                modeloTablaUnicos.addRow(registro);
                contador++;
                i++;
            }while(contador < estructura.length);
            tabla_datos.setModel(modeloTablaUnicos);
        }else{
            //No se selecciono nada...
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo seleccionado anteriormente", 
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_orden_seleccionActionPerformed

    private void busqueda_secuencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqueda_secuencialActionPerformed
         //Aqui haremos la busqueda secuencial... (la cual es mucho mejor para buscar por cualquier campo, menos codigo...)
        if(orden == true || jfile.getSelectedFile() != null){
            Object[] opciones = {"CRN", "CLAVE", "MATERIA", "APELLIDOS", "NOMBRE"}; 
            int seleccion = JOptionPane.showOptionDialog(null, "Por que campo se hara la busqueda", "Campo de busqueda",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opciones, opciones[0]);
            String campo = (String) opciones[seleccion];
            int index[]; //tomamos la informacion aqui y despues la imprimiremos en algo por definir aun...
            String input = null;
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            int e = 1; 
            int y = 0; 
            int contador = 0; 
            String CADENA = null;
            
            switch(seleccion){
                case 0:
                    input = JOptionPane.showInputDialog(null, "Ingrese el CRN");
                    System.out.println("Opción CRN. Valor ingresado: " + input);
                    
                    index = busquedas.secuencialSearch(OrdenDefault, input, seleccion);
                    e = 1; 
                    contador = 0; 
                    CADENA = null; 
                    y = 0; //contador de ceros...
                    if(index[0] == 0){
                        if(orden == false){
                            contador = index[1]; 
                            CADENA  = forAwhileInverso[contador];
                            String registro [] = new String []{"Busqueda secuencial: " + e, CADENA}; 
                            modeloTablaUnicos.addRow(registro);
                            e++; 

                            tabla_datos.setModel(modeloTablaUnicos);
                        }else{
                            contador = index[1]; 
                            CADENA  = forAwhile[contador];
                            String registro [] = new String []{"Busqueda secuencial: " + e, CADENA}; 
                            modeloTablaUnicos.addRow(registro);
                            e++; 

                            tabla_datos.setModel(modeloTablaUnicos);
                        }
                    }else {
                        CADENA  = "No se encontro el dato requerido.";
                        String registro [] = new String []{"Busqueda secuencial: " + e, CADENA}; 
                        modeloTablaUnicos.addRow(registro);
                        e++; 

                        tabla_datos.setModel(modeloTablaUnicos);
                    }
                    
                break;
                
                case 1: 
                    //CLAVE...
                    input = JOptionPane.showInputDialog(null, "Ingrese el CLAVE");
                    System.out.println("Opción CLAVE. Valor ingresado: " + input);
                    
                    index = busquedas.secuencialSearch(OrdenDefault, input, seleccion);
                    e = 1; 
                    contador = 0; 
                    CADENA = null; 
                    y = 0; //contador de ceros...
                    for(int i = 0; i < index.length; i++){
                        if(index[i] != 0){
                            contador = index[i]; 
                            CADENA  = forAwhile[contador];
                            String registro [] = new String []{"Busqueda secuencial: " + e, CADENA}; 
                            modeloTablaUnicos.addRow(registro);
                            e++; 
                        }
                    }

                    tabla_datos.setModel(modeloTablaUnicos);
                break;
                
                case 2: 
                    input = JOptionPane.showInputDialog(null, "Ingrese el MATERIA");
                    System.out.println("Opción MATERIA. Valor ingresado: " + input);
                    
                    index = busquedas.secuencialSearch(OrdenDefault, input, seleccion);
                    e = 1; 
                    contador = 0; 
                    CADENA = null; 
                    y = 0; //contador de ceros...
                    for(int i = 0; i < index.length; i++){
                        if(index[i] != 0){
                            contador = index[i]; 
                            CADENA  = forAwhile[contador];
                            String registro [] = new String []{"Busqueda secuencial: " + e, CADENA}; 
                            modeloTablaUnicos.addRow(registro);
                            e++; 
                        }
                    }

                    tabla_datos.setModel(modeloTablaUnicos);
                break;
                
                case 3: 
                    input = JOptionPane.showInputDialog(null, "Ingrese el APELLIDOS");
                    System.out.println("Opción APELLIDOS. Valor ingresado: " + input);
                    
                    for(int i = 0; i < OrdenDefault.length; i++){
                        System.out.println("Datos: " + OrdenDefault[i]);
                    }
                    
                    index = busquedas.secuencialSearch(OrdenDefault, input, seleccion);
                    e = 1; 
                    contador = 0; 
                    CADENA = null; 
                    y = 0; //contador de ceros...
                    for(int i = 0; i < index.length; i++){
                        if(index[i] != 0){
                            contador = index[i]; 
                            CADENA  = forAwhile[contador];
                            String registro [] = new String []{"Busqueda secuencial: " + e, CADENA}; 
                            modeloTablaUnicos.addRow(registro);
                            e++; 
                        }
                    }

                    tabla_datos.setModel(modeloTablaUnicos);
                    
                break;
                
                case 4: 
                    
                    input = JOptionPane.showInputDialog(null, "Ingrese el NOMBRE");
                    System.out.println("Opción NOMBRE. Valor ingresado: " + input);
                    
                    index = busquedas.secuencialSearch(OrdenDefault, input, seleccion);
                    e = 1; 
                    contador = 0; 
                    CADENA = null; 
                    y = 0; //contador de ceros...
                    for(int i = 0; i < index.length; i++){
                        if(index[i] != 0){
                            contador = index[i]; 
                            CADENA  = forAwhile[contador];
                            String registro [] = new String []{"Busqueda secuencial: " + e, CADENA}; 
                            modeloTablaUnicos.addRow(registro);
                            e++; 
                        }
                    }

                    tabla_datos.setModel(modeloTablaUnicos);
                    
                break;
            }
            
        }else if(jfile.getSelectedFile() == null){
            JOptionPane.showMessageDialog(rootPane, "No hay ningun archivo cargado", 
                        "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_busqueda_secuencialActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        //El chiste de este boton es regresar la tabla a como estaba antes de hacer la busqueda...
        if(jfile.getSelectedFile() != null){
            //Aqui tenemos nuestro set Model... 
            javax.swing.table.DefaultTableModel modeloTablaUnicos= new DefaultTableModel(new String [] {"Numero", "Registro"}, 0);
            
            //lo lee una vez para que la variable no paresca estar null...
            String cad; 
            String[] estructura;
            /*Aqui hay un pedo aun. de cuarquier manera los ordena de mayor a menor, hay que modificar eso ya que
            debe de regresar todo al estado en el que estaban antes de hacer la busqueda...*/
            if(orden == true){
                System.out.println("Opcion orden == true");
                estructura = forAwhile;
            }else{
                System.out.println("Opcion orden == false");
                estructura = forAwhileInverso;
            }
            int contador = 0; 
            int i = 1; 
            String registro[];
            System.out.println("Lo que hay dentro de type: " + type);
            do{
                cad = estructura[contador];

                if("Carga".equals(type)){
                    registro = new String []{"" + i, cad}; 
                }else{
                    registro = new String []{ type + ": " + i, cad}; 
                }
                modeloTablaUnicos.addRow(registro);
                contador++;
                i++;
            }while(contador < estructura.length);
            tabla_datos.setModel(modeloTablaUnicos);
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JMenuItem busqueda_binaria;
    private javax.swing.JMenuItem busqueda_secuencial;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem j_cargar;
    private javax.swing.JMenuItem j_e1a;
    private javax.swing.JMenuItem j_e1b;
    private javax.swing.JMenuItem j_e1c;
    private javax.swing.JMenuItem j_salir;
    private javax.swing.JMenuItem je2;
    private javax.swing.JMenu jmArchivos;
    private javax.swing.JMenu jmBusquedas;
    private javax.swing.JMenu jmEstructrura;
    private javax.swing.JMenu jmOrdennamiento;
    private javax.swing.JMenuItem orden_burbuja;
    private javax.swing.JMenuItem orden_seleccion;
    private javax.swing.JMenuItem orden_shell;
    private javax.swing.JTable tabla_datos;
    // End of variables declaration//GEN-END:variables
}
